# Generated by Django 3.1.5 on 2021-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='./article/%Y%m%d/'),
        ),
    ]
